### PR TITLE
#3 add support for .NET Core compilation

### PR DESCRIPTION
**Pull request by lahma**
- base work to allow both .NET 4.5 and netstandard1.3 compilation
- tests pass using dotnet test 
  *packages.config transformed to project.json 
- rake file _not_ updated
- project.jsons still require authors, version etc

### CODE REVIEW

**Comment by phatboyg** [comment]
So is this built around the just release .NET Core 1.0 bits? Just wanting to verify.

**Comment by lahma** [comment]
Yes, using the released SDK/Visual Studio Tooling. Referenced .NET libraries should be the latest. I hope this helps as starting point at least, I'm willing to help more of course (main goal is to have Core compatible build of Masstransit).

**Comment by phatboyg** [comment]
I could never get this to work, it kept complaining about .NET 4.5.2 dependencies. I've updated the master build to use FAKE, could you possibly take another swing at this one and get whatever I can't figure out worked through?

**Comment by lahma** [comment]
Sure thing, I'll have a look later and report back.

**Comment by lahma** [comment]
I think I got it working now. I rebased against your master and added extra commit for changes listed below.

Changes:
- upgrade NuGet.exe to latest 3.4 to be on the safe side
- change the entire FAKE script to use dotnet tooling which can build both .NET Core and full .NET Framework packages, MSBuild targeting the old solution cannot do that
- now the script uses information from project.json when packaging NuGet package
- I did some tweaks to cleaning (bin and obj folders too) and added githash as assembly metadata

Biggest pitfall here is that you need to also update NewId\project.json when you want to upgrade the NuGet package version. Assembly metadata should come from the shared cs file but dotnet pack lacks the ability to take full version for NuGet package. This might not be such a big problem as what I understand you want to have build numbers only inside the DLLs and as informative.

OK the Appveyor build still fails as it seems to try to run extra step for NUnit. The dotnet test  already handles that and results should be at build_artifacts\nunit-test-results.xml .

Hope this helps, feel free to tweak more and ditch the changes you don't like.

**Comment by phatboyg** [comment]
Okay, I'll try to fix the test running for AppVeyor.

I really want the build version to come from AppVeyor, and automatically update the NuGet package versions. That's really key for me, so figuring that out like it was in Fake would help a lot.

**Comment by lahma** [comment]
OK I'll have another round trying to combine best of both worlds. Packing with NuGet and building with dotnet CLI.

**Comment by phatboyg** [comment]
Fast response, nice :)

I'm excited to get this merged, so I can use it as a pattern for the other projects as well. I learn best by example...

**Comment by lahma** [comment]
Now I'm copying dotnet CLI build results to build_temp then packaging using the old logic. I did however need to change from old nugetVersion function to using just plain Version. The NuGet pack command seems to get confused about feature branch name (file paths) at least when not in master.

I'm also quite a newbie with FAKE (only converted Quartz.NET a moment ago to use it) so there might be still some room for improvement.

**Comment by wallymathieu** [comment]
I've added a second pull request for this issue #8 with the updated csproj format.

**Pull request closed without merging**
