### PR TITLE
NewId on .net core this fixes #3

### LINKED ISSUE #3: Get running on `dotnet` cli / .NET Core
Get NewId running on .net core.

### PR DESCRIPTION
**Pull request by wallymathieu**
Using 2017 version of the csproj format.

### CODE REVIEW

**Comment by wallymathieu** [comment]
The SolutionVersion.cs looks like an obsolete construct. The easiest way would be to either enter that information in the NewId csproj or have an xml file then include that file in csproj.

**Comment by wallymathieu** [comment]
Note that the tests are currently only built using .net45, due to https://github.com/nunit/dotnet-test-nunit/issues/108

**Comment by phatboyg** [comment]
Cool, I'll start looking at what you did here to carry it into the other projects downstream.

**Comment by andymac4182** [comment]
From a quick look it appears like it wouldn't be super hard to migrate to XUnit which would allow for running of tests against all target frameworks. I am happy to look at doing that once this is merged or on a branch if that works out to be a good idea 😄

**Comment by wallymathieu** [comment]
I've mostly been migrating to xunit for a lot of projects for that reason. 😄

**Comment by phatboyg** [comment]
Doesn't NUnit support Core as well?

**Comment by wallymathieu** [comment]
It does, but there is not a new vs 2017 adapter yet.

**Comment by andymac4182** [comment]
Support for dotnet core and vs2017 from what I have used has been more integrated in xUnit. It would be great to look at moving to just a single solution file as well similar to the change json.net just completed.

**Comment by phatboyg** [comment]
Yeah, a single solution would be ideal, good to hear others have done it. I'll look at what he did.

**Comment by wallymathieu** [comment]
Note that there is only one solution here. The assumption is that the tests on net45 are works close enough on core, why the tests are only compiled to net452 (while the newid assembly is specified for two .net versions: net452 and netstandard1.6). Later on you could enable multi format tests (when nunit is more stable for core).

**Comment by phatboyg** [comment]
Right on, makes sense. Thanks!

**Comment by andymac4182** [comment]
@wallymathieu Apologies about the single solution comment. I was thinking of GreenPipes which has 2.

**Comment by wallymathieu** [comment]
No worries. It should be straightforward to fix GreenPipes so that there is only one solution.

**Comment by andymac4182** [comment]
@wallymathieu I have started to apply the same changes through to GreenPipes. https://github.com/MassTransit/GreenPipes/pull/3

**Comment by phatboyg** [comment]
Very nice. I should have time to get 2017 installed this week and get familiar with this to merge it into master.

**Comment by andymac4182** [comment]
@wallymathieu Curious if there is something in NewId that requires `netstandard1.6` over one of the lower versions?

**Comment by wallymathieu** [comment]
Probably not. I usually target ```netstandard1.6``` since it's the default for libraries.

**Comment by phatboyg** [comment]
This is all merged/rebased/etc.

**Pull request closed without merging**
