### PR TITLE
Fixes: Collisions of Ids #15

### PR DESCRIPTION
**Pull request by OidaTiftla**
If you insert `System.Console.WriteLine("Enter Generator ctor");` directly after the constructor of `NewIdGenerator`:

```csharp
public NewIdGenerator(ITickProvider tickProvider, IWorkerIdProvider workerIdProvider, IProcessIdProvider processIdProvider = null, int workerIndex = 0)
{
    System.Console.WriteLine("Enter Generator ctor");
    _tickProvider = tickProvider;
```

And then execute the test script from https://github.com/phatboyg/NewId/issues/15#issuecomment-509897250:

> Hi @phatboyg,
> 
> Here's the code sample that was used to show collisions.
> 
> ```
>     static void Main(string[] args)
>     {
>         var c1 = new ConcurrentBag<Guid>();
> 
>         Parallel.For(0, 5000000, (i) =>
>         {
>             c1.Add(NewId.NextGuid());
>         });
> 
>         var groups = c1.GroupBy(g => g).Where(x => x.Count() != 1).ToList();
>         var maxGrouping = groups.Max(x => x.Count());
>         
>         Console.WriteLine($"Collisions: {groups.Count()}");
>         Console.WriteLine($"MaxGroupCollisions: {maxGrouping}");
>     }
> ```
> 
> I know in most cases GUIDs will be generated on different PODs and threads. However, in our case, we have a conversation queue that can only be read by a single service. We can experience anywhere between 450K - 800K messages a daily that need to be logged using unique sequential GUIDs.
> 
> Hope this help,
> 
> codematrix

You now will see something like this in the console:

```
Enter Generator ctor
Enter Generator ctor
Enter Generator ctor
Enter Generator ctor
Enter Generator ctor
```

So there now might exist multiple generators on different threads. And those multiple generators might lead to collisions.

To avoid this I introduces `_getGenerator()` which is thread-safe. Then the console output is only:

```
Enter Generator ctor
```

### CODE REVIEW

**Comment by phatboyg** [comment]
Did you benchmark with dotTrace to measure the performance impact?

**Comment by phatboyg** [comment]
I checked, it's fine.

**Comment by OidaTiftla** [comment]
Thanks!

**Comment by OidaTiftla** [comment]
I saw there are currently more changes in the merge/rebased commit than I originally committed:

```csharp
diff --git a/src/NewId/NewId.cs b/src/NewId/NewId.cs
index f1f01dd..9d2c040 100644
--- a/src/NewId/NewId.cs
+++ b/src/NewId/NewId.cs
@@ -78,7 +78,7 @@ namespace MassTransit
             _d = a;
         }

-        static IWorkerIdProvider WorkerIdProvider => _workerIdProvider ??= new BestPossibleWorkerIdProvider();
+        static IWorkerIdProvider WorkerIdProvider => _workerIdProvider ?? (_workerIdProvider = new BestPossibleWorkerIdProvider());

         static IProcessIdProvider ProcessIdProvider => _processIdProvider;

@@ -87,7 +87,7 @@ namespace MassTransit
 #if NET452
             get { return _tickProvider ?? (_tickProvider = new StopwatchTickProvider()); }
 #else
-            get { return _tickProvider ??= new DateTimeTickProvider(); }
+            get { return _tickProvider ?? (_tickProvider = new DateTimeTickProvider()); }
 #endif
         }

```

**Comment by OidaTiftla** [comment]
Ah sorry, I missed that there is a new syntax possible in C#.

`??=` 👍 very cool syntax

**Comment by phatboyg** [comment]
Yeah I typically clean up and rebase back to a single commit to give credit

**Comment by OidaTiftla** [comment]
Thanks and I did learn some new syntax 😃

**Pull request closed without merging**
