### PR TITLE
Ordering SQL vs ToSequentialGuid()

### PR DESCRIPTION
**Pull request by OidaTiftla**
Hi, great library. It solved my problem of generating sequential GUIDs.

After using it for some time I noticed that the ordering of `SqlGuid` and `ToSequentialGuid()` is not always the same (in some edge cases).

The main problem I had was the following scenario, when generating more than 256 GUIDs using the array generation method:

```csharp
using MassTransit;
using System;
using System.Data.SqlTypes;
using System.Linq;

var array = NewId.Next(512);
var ids = array.Select(x => new SqlGuid(x.ToGuid().ToByteArray())).ToList();
Console.WriteLine("| i   | guid                                 |");
Console.WriteLine("| --- | ------------------------------------ |");
foreach (var x in ids) {
    var originalIndex = ids.IndexOf(x);
    Console.WriteLine($"| {originalIndex,3} | {x,36} |");
}

Console.WriteLine("Sorted:");
var ordered = ids.OrderBy(x => x).ToList();
Console.WriteLine("| i   | guid                                 |");
Console.WriteLine("| --- | ------------------------------------ |");
foreach (var x in ordered) {
    var originalIndex = ids.IndexOf(x);
    Console.WriteLine($"| {originalIndex,3} | {x,36} |");
}
```

Note that the IDs are not sorted in the order they were created.

The format is `mmmmssss-mmmm-mmmm-tttt-tttttttttttt`. Where `m` is the MAC-address, `t` the timestamp and `s` the sequence counter. So the interessting part for this problem is the `s` (because all others stay the same). (I've removed my MAC-address and replaced it with `x`.)

| i   | guid                                 |
| --- | ------------------------------------ |
| 0   | xxxx0000-xxxx-xxxx-15ad-08d89a158ab8 |
| 1   | xxxx0001-xxxx-xxxx-15ad-08d89a158ab8 |
| 2   | xxxx0002-xxxx-xxxx-15ad-08d89a158ab8 |
| 3   | xxxx0003-xxxx-xxxx-15ad-08d89a158ab8 |
| ... | ...                                  |
| 252 | xxxx00fc-xxxx-xxxx-15ad-08d89a158ab8 |
| 253 | xxxx00fd-xxxx-xxxx-15ad-08d89a158ab8 |
| 254 | xxxx00fe-xxxx-xxxx-15ad-08d89a158ab8 |
| 255 | xxxx00ff-xxxx-xxxx-15ad-08d89a158ab8 |
| 256 | xxxx0100-xxxx-xxxx-15ad-08d89a158ab8 |
| 257 | xxxx0101-xxxx-xxxx-15ad-08d89a158ab8 |
| 258 | xxxx0102-xxxx-xxxx-15ad-08d89a158ab8 |
| 259 | xxxx0103-xxxx-xxxx-15ad-08d89a158ab8 |
| ... | ...                                  |
| 508 | xxxx01fc-xxxx-xxxx-15ad-08d89a158ab8 |
| 509 | xxxx01fd-xxxx-xxxx-15ad-08d89a158ab8 |
| 510 | xxxx01fe-xxxx-xxxx-15ad-08d89a158ab8 |
| 511 | xxxx01ff-xxxx-xxxx-15ad-08d89a158ab8 |

After sorting it using the `SqlGuid` I got:

| i   | guid                                 |
| --- | ------------------------------------ |
| 0   | xxxx0000-xxxx-xxxx-15ad-08d89a158ab8 |
| 256 | xxxx0100-xxxx-xxxx-15ad-08d89a158ab8 |
| 1   | xxxx0001-xxxx-xxxx-15ad-08d89a158ab8 |
| 257 | xxxx0101-xxxx-xxxx-15ad-08d89a158ab8 |
| 2   | xxxx0002-xxxx-xxxx-15ad-08d89a158ab8 |
| 258 | xxxx0102-xxxx-xxxx-15ad-08d89a158ab8 |
| 3   | xxxx0003-xxxx-xxxx-15ad-08d89a158ab8 |
| 259 | xxxx0103-xxxx-xxxx-15ad-08d89a158ab8 |
| ... | ...                                  |
| 252 | xxxx00fc-xxxx-xxxx-15ad-08d89a158ab8 |
| 508 | xxxx01fc-xxxx-xxxx-15ad-08d89a158ab8 |
| 253 | xxxx00fd-xxxx-xxxx-15ad-08d89a158ab8 |
| 509 | xxxx01fd-xxxx-xxxx-15ad-08d89a158ab8 |
| 254 | xxxx00fe-xxxx-xxxx-15ad-08d89a158ab8 |
| 510 | xxxx01fe-xxxx-xxxx-15ad-08d89a158ab8 |
| 255 | xxxx00ff-xxxx-xxxx-15ad-08d89a158ab8 |
| 511 | xxxx01ff-xxxx-xxxx-15ad-08d89a158ab8 |

This pull request is not yet ready for merge, but I've created some test cases to reproduce the ordering issue.

If you'd like I will extend this merge-request so the ordering will preserve the same?

### CODE REVIEW

**Comment by phatboyg** [comment]
So did you other PR resolve this issue? It's been merged into the develop branch btw.

**Comment by OidaTiftla** [comment]
The other PR does not resolve this one.

Should I try to fix this one and let you see if you'd like to merge it? As far is I understand the code currently, there might be some more changes necessary to resolve this sorting issue.

**Comment by phatboyg** [comment]
So, my concern is that the GUIDs should be sequential already, so I'm not sure how you're getting them out of order.

**Comment by phatboyg** [comment]
Oh, I see, the sequence number needs to be byte-swapped for the sequential Guid conversion.

**Comment by OidaTiftla** [comment]
Yes and some more bytes may need to be shuffled.

I found this on [docs.microsoft.com](https://docs.microsoft.com/en-us/archive/blogs/dbrowne/how-to-generate-sequential-guids-for-sql-server-in-net)

**Comment by OidaTiftla** [comment]
This might also be interesting when solving this: [NEWSEQUENTIALID (Transact-SQL)](https://docs.microsoft.com/de-de/sql/t-sql/functions/newsequentialid-transact-sql?view=sql-server-ver15)

**Comment by OidaTiftla** [comment]
I figured out the following ordering with `SqlGuid`:

- `0f` = most significant byte
- `00` = least significant byte
- `00010203-0405-0607-0908-0f0e0d0c0b0a`

As I found out the method `ToSequentialGuid()` outputs a format `tttttttt-tttt-tttt-mmmm-mmmm-mmmmssss`.

Where `m` is the MAC-address, `t` the timestamp and `s` the sequence counter.

Currently `SqlGuid` sorts similar to this `tttttttt-tttt-tttt-mmmm-mmmm-ssssmmmm`.

With the byte swapping applied from [docs.microsoft.com](https://docs.microsoft.com/en-us/archive/blogs/dbrowne/how-to-generate-sequential-guids-for-sql-server-in-net) it would result in the expected form `tttttttt-tttt-tttt-mmmm-mmmm-mmmmssss`.

What do you think about that change?

**Comment by phatboyg** [comment]
https://github.com/phatboyg/NewId/blob/master/src/NewId.Tests/LongTerm_Specs.cs#L10

This unit test already checks SqlGuid ordering, so...

**Comment by OidaTiftla** [comment]
Yes that's correct. But it only changes the timestamp, not the other bytes (sequence number and MAC-address) which also participate in the ordering.

I created two test when the sequence number changes and all other parts stay the same:
- for `SqlGuid`: https://github.com/OidaTiftla/NewId/blob/933569dd3442acf43c2475c6568f09c3c05c8be2/src/NewId.Tests/Order_Specs.cs#L14
- and for `ToSequentialGuid()`: https://github.com/OidaTiftla/NewId/blob/933569dd3442acf43c2475c6568f09c3c05c8be2/src/NewId.Tests/Order_Specs.cs#L37

I also created tests for changing the MAC-address and process ID, but I think they don't need to be ordered correctly (as far as I understand they are only there for uniqueness).

**Comment by phatboyg** [comment]
Great, just wanted to point it out. If we can fix the sequence number for this use case, i think that's fine. I don't want to expand it beyond that.

**Comment by OidaTiftla** [comment]
Okay, so I have to dig into the code. I don't know if I have enough time today, but I will update this PR in the next days.

PS: By the way I was very surprised about how well maintained this repo is and that my other PR was resolved in under two hours after I created it 😄. Very well done 👍.

**Comment by OidaTiftla** [comment]
Sorry for the late reply.

I added some unit tests to ensure compatibility with previous behaviour.

**Edit:**
I also changed `NewId n = NewId.Next();` to `NewId n = NewId.Next(2)[1];` in some relevant unit tests to ensure sequence number is not 0x0000. So the tests will fail if my implementation of the byte swapping was not done correctly.

**Comment by phatboyg** [comment]
Merged, released as 3.0.3

**Comment by OidaTiftla** [comment]
Thanks :)

And merry Christmas.

**Pull request closed without merging**
